# Generated by Django 5.0.14 on 2026-06-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'event_name'], name='events_even_project_1bb905_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'timestamp'], name='events_even_project_ae666e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'user_id'], name='events_even_project_da8e68_idx'),
        ),
    ]
