# Generated by Django 5.0.14 on 2026-06-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('dau', 'Daily Active Users'), ('wau', 'Weekly Active Users'), ('mau', 'Monthly Active Users'), ('retention', 'Retention'), ('funnel', 'Funnel'), ('cohort', 'Cohort'), ('trend', 'Event Trend')], db_index=True, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FunnelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('step_order', models.IntegerField()),
                ('step_name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['date', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='FunnelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_date', models.DateField()),
                ('period', models.CharField(max_length=10)),
                ('retained_users', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['cohort_date'],
            },
        ),
    ]
