# Generated by Django 5.0.14 on 2026-06-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_results', to='projects.project'),
        ),
        migrations.AddField(
            model_name='dailyactiveuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_active_users', to='projects.project'),
        ),
        migrations.AddField(
            model_name='eventcount',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_counts', to='projects.project'),
        ),
        migrations.AddField(
            model_name='funnelanalysis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_analyses', to='projects.project'),
        ),
        migrations.AddField(
            model_name='funneldefinition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_definitions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='funnelanalysis',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analytics.funneldefinition'),
        ),
        migrations.AddField(
            model_name='retentioncurve',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_curves', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='analyticsresult',
            index=models.Index(fields=['project', 'metric_type'], name='analytics_a_project_7e27c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactiveuser',
            unique_together={('project', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='eventcount',
            unique_together={('project', 'event_name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='retentioncurve',
            unique_together={('project', 'cohort_date', 'period')},
        ),
    ]
