# Generated by Django 5.0.14 on 2026-07-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transaction_count', models.IntegerField(default=0)),
                ('subscription_count', models.IntegerField(default=0)),
                ('refund_count', models.IntegerField(default=0)),
                ('dau', models.IntegerField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('avg_churn_risk', models.FloatField(default=0.0)),
                ('high_risk_user_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_revenues', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
