# Generated by Django 5.0.14 on 2026-07-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('window_start', models.DateField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('score', models.FloatField()),
                ('threshold', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, default='')),
                ('top_features', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-window_start'],
                'indexes': [models.Index(fields=['project_id', 'window_start'], name='dashboard_a_project_341f32_idx'), models.Index(fields=['project_id', 'status'], name='dashboard_a_project_e368db_idx')],
            },
        ),
    ]
