# Generated by Django 5.0.14 on 2026-06-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('discovery', 'Discovery'), ('purchase_intent', 'Purchase Intent'), ('checkout', 'Checkout'), ('conversion', 'Conversion'), ('engagement', 'Engagement'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_mappings', to='projects.project')),
            ],
            options={
                'ordering': ['event_name'],
                'unique_together': {('project', 'event_name')},
            },
        ),
    ]
