# Generated by Django 5.0.14 on 2026-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmapping',
            name='used_in_funnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventmapping',
            name='category',
            field=models.CharField(choices=[('authentication', 'Authentication'), ('discovery', 'Discovery'), ('engagement', 'Engagement'), ('purchase_intent', 'Purchase Intent'), ('checkout', 'Checkout'), ('conversion', 'Conversion'), ('exit', 'Exit'), ('support', 'Support'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
